language: node_js
node_js:
 - 5.9.0
before_install:
 - npm install -g dredd

script:
 - dredd apiary.apib http://excel-inc.acmr.com.cn:20064/$TRAVIS_BRANCH/ -j apiaryApiKey:029da612a1134e550900fa79013d3ad3 -j apiaryApiName:fengniao
cache:
   directories:
   - node_modules
