FORMAT: 1A
HOST: http://excel-inc.acmr.com.cn:20064/master/

# Interaction API of Sunbeam

> 为保证我们的设计思想和开发成果保持一致，采用互动性文档进行的结果验证，其功能包含几个方面
> - 文档的生成
> - 数据请求结果记录
> - 在线编辑文档内容
> - 模拟数据，正式环境数据
> - 文档和开发结果匹配测试


## 阅读&使用须知

### 名词释义

> - `SUNBEAM_AUTHENTIC_KEY`: 当前页面的唯一`SBMID`, 不管是新建或更新表
>
> - 默认值: 列宽`72px`、行高`20px`
>
> - **[同步操作]** : 就是等待后台返回该请求结果，前台才会继续执行后续操作
>


### REST命名规则

> `url`的组成结构： `{根目录}/{模块}/{主操作- ?子操作}` 
> 模块有4中类型，`Book`,`Sheet`,`Row|Col`,`Cell`
> 操作根据具体层级关系递进，中间用 `-` 间隔
>> 如 设置字体颜色，`http://www.sunbeam.com/cell/font-color`


### 传递参数的意义解释

> 交互阶段传入的坐标信息都是`sort`值，即：后台数据存储的行列索引值
> 整行、列操作时，最大值: -1 表示
>> 如：第五列
>>```
>> {
>>      startRow: 0,
>>      startCol: 4,
>>      endRow：-1,
>>      endCol: 5
>>}
>>```

### 接口返回码

| 接口码        | 释义        | 应用的场景           |
| ------------- |-------------| ---------------------|
| 413           | 资源不能处理| 文件上传，RMI远程调用|
| 400           | 参数错误    | X-Book-Id或X-Step参数缺失|

> 以 `HTTP Status Code` 码为标准
q
### 请求类型

> - 多个之间没有任何关系，即：独立发送返回，无限制
> - 需要后台做处理并，需要等待返回值，如：粘贴
> - 操作页面上 **未知** 区域并，需要等待返回值，如：数据验证
>
> **后两种类型，请求必须等待数据返回后，才执行后续功能**

<!--### 留存的疑问-->

<!--> - position的参数都是什么意思？-->
<!--> - 没有传递变量的功能，如何解决？-->

<!--### 困难解决记录-->

<!--> - optional 和 required的区别，和作用-->
<!-->> optional后面必须跟Member成员-->
<!-->> required是必须参数，不能选择-->
<!-->-->
<!--> - 怎么进行值传递，参数变量-->
<!-->>API的point功能可以实现-->
<!--### 文档缺陷-->

<!--> 由于文档没有实现`Headers`的重用-->
<!--> 所有我们在Mock时，自定在`Headers`里面指定`FN-Step`、`FN-ID`信息-->

# Group Opration Row or Col
    
    > - 行、列暂时不支持批量操作

## Rows Opration [/row/{actionType}]

    行操作，插入，删除，隐藏，显示，行高调整

+ Parameters
    + actionType: `plus` (enum[string]) - 动作类型
        + Members
            + `plus`
            + `reduce`
            + `hide`
            + `show`

### Single Insert or Delete Row [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
            
    + Attributes (Row Number)
    
+ Response 200
    
## Adjust Single Row Height [POST /row/adjust]

    行高调整
    
+ Request (application/json)
    + Attributes (Row Number)
        + offset: `87`(number) - 调整后的值,最小值为5px
    
+ Response 200

## Cols Opration [/col/{actionType}]

    列操作，插入，删除，隐藏，显示，调整
    
+ Parameters
    + actionType: `plus` (enum[string]) - 动作类型
        + Members
            + `plus`
            + `reduce`
            + `hide`
            + `show`

### Single Insert or Delete Col [POST]
    
+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes (Col Number)
    
+ Response 200

## Adjust Single Col Width [POST /col/adjust]

    列宽调整
    
+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes (Col Number)
        + offset: `87`(number) - 调整后的值,最小值为5px
    
+ Response 200

# Group Opration Cells

    > - 该部分针对单元格的处理（即：没有内容也有效果情况）
    > - 单元格所有操作都要支持多选区域
    
## Merge or Split [/cell/{actionType}]

+ Parameters
    + actionType: `merge`(string) - 动作类型
        + Members
            + `merge`
            + `split`

### Merge or Split Cells [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes
        + coordinate (array[Coordinate properties])

+ Response 200

## Borders [/cell/border]

### Set Borders Style [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes
        + coordinate (array[Coordinate properties])
        + direction: `top` (enum[string])
            + Members
                + `top`
                + `right`
                + `bottom`
                + `left`
                + `all`
                + `outer`
                + `none`

+ Response 200

## Set Background [/cell/bg]
    
    单元格背景颜色
    
### Single Background Color [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes 
        + coordinate (array[Coordinate properties])
        + color: `rgb(73, 68, 41, 0)` (string) - 编码遵循RGBA的规则编码
    
+ Response 200

## Lock State [/cell/lock]

    锁定单元格是否为保护状态
    
### Lock Cells Satatus [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
            
    + Attributes
        + coordinate (array[Coordinate properties])
        + lock: true (boolean) - 默认为锁定状态，用`true`代表，`false`为非锁定状态
        
+ Response 200

        
# Group Cell Data Opration

    针对单元格的内容处理的操作，有内容时才有效果

## Automatic Wrap [/cell/wordwrap]

### Set Text Auto Wrap [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes 
        + coordinate (array[Coordinate properties])
        + auto: false (boolean) - 默认不是自动换行，true为自动换行

+ Response 200

## Align Transverse [/cell/align-landscape]

### Set transverse Style [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes 
        + coordinate (array[Coordinate properties])
        + align: `left` (enum[string])
            + Members
                + `left`
                + `center`
                + `right`
+ Response 200

## Align Vertically [/cell/align-portrait]

### Set vertically Style [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes 
        + coordinate (array[Coordinate properties])
        + align: `top` (enum[string])
            + Members
                + `top`
                + `middle`
                + `bottom`
+ Response 200

## Format Cells Type [/cell/format]

    单元格的类型设置

### Setting Cells Type [POST]
    
+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes 
        + coordinate (array[Coordinate properties])
        + format:`routine`(enum[string]) - 常规类型
            + Members
                + `routine` - 常规类型
                + `text`
                + `number`
                + `date`
                + `currency`
                + `percent`
        + express: `###.##`(string) - 格式表达式，限制性的解释POI中的规则，如果超出解释范围就为默认类型

+ Response 200



## Add or Update Comments [/cell/comment-plus]

### Setting Data Comments for explain [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes
        + coordinate (array[Coordinate properties])
        + comment: `<script>console.log("1")</script>`(string, required) - 输入的内容，内容需要经过转码的，防止代码攻击

+ Response 200

## Delete Comments [/cell/comment-reduce]

### Delete Data Comments [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes 
        + coordinate (array[Coordinate properties])

+ Response 200

## Set Content [/cell/data-set]

    单元格写入内容

### Setting Data Content [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes (Coordinate)
        + content: `<script>console.log("1")</script>`(string) - 输入的内容，内容需要经过转码的，防止代码攻击

+ Response 200

## Clean Content [/cell/data-clean]
    
    清除单元格内容

### Clean Data Content [POST]

+ Request (application/json)

    + Headers
            
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
            
    + Attributes
        + coordinate (array[Coordinate properties])
    
+ Response 200


# Group Cells Font Style Opration

    针对单元格内的字体的接口

## Font Size [/cell/font-size]

### Update Font Size [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes
        + coordinate (array[Coordinate properties])
        + size: `12`(number) - 字体默认是12pt，最大值48，都是以pt为单位
        
+ Response 200

## Font Family [/cell/font-family]

### Update Font Family [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes 
        + coordinate (array[Coordinate properties])
        + family: `宋体`(enum[string]) - 字体默认是宋体，其余字体风格是枚举类型
            + Members
                + `宋体`
                + `微软雅黑`
                + `黑体`
                + `Tahoma`
                + `Arial`
                + `楷体`
        
+ Response 200

## Font Weight [/cell/font-weight]

### Update Font Weight [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes
        + coordinate (array[Coordinate properties])
        + weight: false (boolean) - 默认非粗体，true是粗体
        
+ Response 200

## Font Italic [/cell/font-italic]

### Update Font Italic [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes
        + coordinate (array[Coordinate properties])
        + italic: false (boolean) - 默认为非斜体
        
+ Response 200

## Font Color [/cell/font-color]

### Update Font Color [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes
        + coordinate (array[Coordinate properties])
        + color: `#000` (string) - 编码遵循RGB的规则编码
    
+ Response 200

## Font Underline [/cell/font-underline]

### Update Font Underline [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
        
    + Attributes
        + coordinate (array[Coordinate properties])
        + underline: 1 (number) - 默认为没有下划线，1：单下划线，0：无
        
+ Response 200


# Group Sheet Opration

## Table Paste [/sheet/paste]

    [同步操作]

### Paste All Info to Any Where [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes (Operation Coordinate)
        + colLen: 1 (number) - 粘贴数据的列数
        + rowLen: 1 (number) - 粘贴数据的行数
        + pasteData (array[Paste Object]) - 被格式化完的数据
        
+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + isLegal: true(boolean) - 是否合法
    
+ Response 400

## Table Cut & Copy [/sheet/{actionType}]
    
+ Parameters
    + actionType: `cut`(string)
        这个动作是剪切或者复制，这个动作的触发只能在excel出现，跟外部交互的操作都是粘贴操作，
        由于浏览器的保护，数据不能获取被剪切到外部的事件
        + Members
            + `cut`
            + `copy`

### Cut or Copy Info to Any Where [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes
        + orignal (Coordinate properties) - 数据原来的位置
        + target (Operation Coordinate)
        
+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + isLegal: true(boolean) - 是否合法

+ Response 400

## Frozen View [/sheet/frozen]

### Frozen Position [POST]

    在冻结首行、列时，位置会根据不同的情况，用`-1`代表
    
+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes (Operation Coordinate) 
        + viewRow: 2 (number) - 冻结时，用户可以看到范围，行编号
        + viewCol: 2 (number) - 冻结时，用户看见的范围，列编号
        
+ Response 200

## Unfrozen View [/sheet/unfrozen]

    解除冻结视图

### UnFrozen Position [GET]
    
+ Request

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7

+ Response 200

## Undo [/sheet/undo]

    后退操作
    
### Undo Oprtaion [GET]

+ Request

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7

+ Response 200

## Redo [/sheet/redo]

    前进操作
    
### Redo Opration [GET]

+ Request

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7

+ Response 200

## Protect Sheet View [/sheet/protect]
    
    > - 保护工作表
    > - [同步操作]

### Current View Protect Status [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes
        + protect: true (boolean) - 是否保护工作表，true是保护，false不保护
        + passwd: `String` (string) - 解锁保存密码，（暂时传输明文），没有密码时，不传。密码位数限制，4-18位。
        
+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + isLegal: true (boolean) - 是否可以上锁 或 解锁 

+ Response 400

## Validate Cells Content & Rule [/sheet/validate-set]
    
    设置数据验证规则

### Set Data Validate [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes
        + coordinate (array[Coordinate properties])
        + rule (Vaildate Object)
        
+ Response 200 

+ Response 400

## Rule Information [/sheet/validate-rule]

    规则内容

### Rule Information For Current Coordinate [POST]

+ Request (application/json)

    + Headers
            
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
            
    + Attributes (Operation Coordinate)
    
+ Response 200 (application/json;charset=utf-8)
    + Attributes
        + rule (Vaildate Object)
        + index: 1 (number) - 规则索引

## Rule & Result Information  [/sheet/validate-full]

    规则内容和数据源结果

### All Options And Rule Information [POST]

+ Request (application/json)

    + Headers
            
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
            
    + Attributes (Operation Coordinate)
    
+ Response 200 (application/json;charset=utf-8)

    + Attributes
        + rule (Vaildate Object)
        + index: 1 (number) - 规则索引
        + expResult: 1,2,4,5 (array) - 所有选项


## Load Area By PX [/sheet/area]

    [同步操作]

### Load Area Information [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
        
    + Attributes (Area px Info)
        
+ Response 200 (application/json;charset=utf-8)

    + Body
    
            {
                cells: [{
                    border: {
                        all: false,
                        bottom: false,
                        left: false,
                        none: false,
                        outer: false,
                        right: false,
                        top: false
                    },
                    content: {
                        alignCol: "bottom",
                        alignRow: "left",
                        bold: false,
                        color: "rgba(0,0,0,1)",
                        displayTexts: "123.00",
                        family: "SimSun",
                        italic: false,
                        size: 11,
                        texts: "123",
                        underline: 0,
                        wordWrap: false,
                        type: "number",
                        express: "###.##",
                        background: "rgb(23,54,93)",
                        locked: false
                    },
                    customProp: {
                        highlight: false,
                        comment: "mark contexts"
                    }
                }],
                gridLineRow: [{
                    alias: "26",
                    hidden: false,
                    sort: 25,
                    top: 1100,
                    height: 19,
                    props: {
                        border: {},
                        content: {},
                        customProp: {},
                    }
                }],
                gridLineCol: [{
                    alias: "56",
                    left: 1750,
                    width: 69,
                    hidden: false,
                    sort: 55,
                    props: {
                        border: {},
                        content: {},
                        customProp: {}
                    }
                }],
                validate: [{
                    rule: {
                        formula1: "3",
                        formula2: "444",
                        index: 1,
                        type: 6
                    },
                    coordinates: [{
                        startCol: 6,
                        startRow: 1,
                        endCol: 6,
                        endRow: 1
                    }]
                }]
            }
        
    + Schema
    
            {
                type: "object",
                properties: {
                    cells: {
                        type: "array",
                        items: {
                            type: "object",
                            properties: {
                                border: {
                                    type: "object",
                                    description: "border不包含在层的div内，所以属性独立出来"
                                },
                                content: {
                                    type: "object",
                                    properties: {
                                        alignCol: {
                                            type: "string",
                                            description: "可能值：bottom | top | middle"
                                        },
                                        alignRow : {
                                            type: "string",
                                            description: "可能值：left | center | right"
                                        },
                                        displayTexts: {
                                            type: "string",
                                            description: "经过处理后的内容(格式化、计算等...之后的结果)"
                                        },
                                        family: {
                                            type: "string",
                                            description: "所有字体都用英文，不能用中文的`宋体`，以免产生编码问题"
                                        },
                                        texts: {
                                            type: "string",
                                            description: "用户输入的内容"
                                        },
                                        underline: {
                                            type: "number",
                                            description: "用0的，是考虑到可能还有双下划线的情况, 0:没有，1: 单线 2：双线"
                                        },
                                        type: {
                                            type: "string",
                                            description: "可能的值：number | text | normal | currency"
                                        },
                                        express: {
                                            type: "string",
                                            description: "表达式需要构建一个完整的解释器，用来表示数据格式"
                                        }
                                    }
                                },
                                customProp: {
                                    type: "object",
                                    description: "特殊的属性:第三方特殊要求"
                                }
                            }
                        }
                    },
                    gridLineRow: {
                        type: "array",
                        items: {
                            type: "object",
                            properties: {
                                sort: {
                                    type: "number",
                                    description: "这个对象在java端，排序完的顺序索引"
                                },
                                props: {
                                    type: "object",
                                    description: "引用自cell的属性"
                                }
                            }
                        }
                    },
                    validate: {
                        type: "array",
                        description: "数据验证对象也是根据位置判断，逐步的返回规则"
                        items: {
                            type: "object",
                            properties: {
                                rule: {
                                    type: "object",
                                    properties: {
                                        formula1: {
                                            type: "string",
                                            description: "如果有一个值，就只返回formula1"
                                        },
                                        index: {
                                            type: "number",
                                            description: "这个作用忘了！！, 等后续补充"
                                        },
                                        type: {
                                            type: "number",
                                            description: "根据类型的不同，给出的枚举值"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }


# Group Table Opration

## Book Reload [/reload]

### Reload All Info [POST]

+ Request (application/json)

    + Headers
    
            X-Book-Id: 28b60797-8457-4410-8fac-db1161839cc7
    
    + Attributes (Area px Info)

+ Response 200 (application/json;charset=utf-8)

    + Body
            
            {
                name: "new book",
                sheets: [{
                    name: "new sheet",
                    maxColAlias: 27,
                    maxRowAlias: 101,
                    maxColPixel: 1819,
                    maxRowPixel: 1999,
                    viewRowAlias: "1",
                    viewColAlias: "1",
                    cells: [{
                        border: {
                            all: false,
                            bottom: false,
                            left: false,
                            none: false,
                            outer: false,
                            right: false,
                            top: false
                        },
                        content: {
                            alignCol: "bottom",
                            alignRow: "left",
                            bold: false,
                            color: "rgba(0,0,0,1)",
                            displayTexts: "",
                            family: "SimSun",
                            italic: false,
                            size: 11,
                            texts: "",
                            underline: 0,
                            wordWrap: false,
                            type: "number",
                            express: "###.#",
                            background: "rgb(23,54,93)",
                            locked: false
                        },
                        customProp: {
                            highlight: false,
                            comment: "mark contexts"
                        },
                        occupy: {
                            row: ["6"],
                            col: ["1"]
                        }
                    }],
                    gridLineRow: [{
                        alias: "26",
                        hidden: false,
                        sort: 25,
                        top: 1100,
                        height: 19,
                        props: {
                            border: {},
                            content: {},
                            customProp: {},
                        }
                    }],
                    gridLineCol: [{
                        alias: "56",
                        left: 1750,
                        width: 69,
                        hidden: false,
                        sort: 55,
                        props: {
                            border: {},
                            content: {},
                            customProp: {}
                        }
                    }],
                    sort: 0,
                    protect: false,
                    validate: [{
                        rule: {
                            formula1: "3",
                            formula2: "444",
                            index: 1,
                            type: 6
                        },
                        coordinates: [{
                            startCol: 6,
                            startRow: 1,
                            endCol: 6,
                            endRow: 1
                        }]
                    }],
                    frozen: {
                        colAlias: "5",
                        rowAlias: "7"
                    }
                }]
            }

    + Schema
    
            {
                type: "object",
                properties: {
                    sheets: {
                        type: "array",
                        items: {
                            type: "object",
                            description: "返回对象里的cells、gridLineCol、gridLineRow、validate内容和area请求一致"
                            properties: {
                                maxColAlias: {
                                    type: "number",
                                    description: "列别名目前的最大值"
                                },
                                maxColPixel: {
                                    type: "number",
                                    description: "当前表格最大的列像素值"
                                },
                                viewColAlias:{
                                    type: "string",
                                    description: "用户关闭页面时候，看到最上角坐标位置。作用： 数据定位还原、冻结。目前只在冻结用到"
                                },
                                sort: {
                                    type: "numbner",
                                    description: "当前sheet所在的索引位置，目前默认是0"
                                },
                                frozen: {
                                    type: "object",
                                    properties: {
                                        colAlias: {
                                            type: "string",
                                            description: "冻结的列位置别名,如果只冻结行，列返回-1"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        

# Data Structures

## Sheet Identify (object) - 单个sheet的ID标识
<!--
暂时弃用
+ sheetId: `1` (string) - 字符串类型的sheetId，自增的整数
-->

## Col Number
+ col: 1(number) - 列号

## Row Number
+ row: 3(number) - 行号

## Area px Info (object)
+ top: 1117 (number) - 请求区域的顶部像素
+ bottom: 1537 (number) - 底部
+ left: 0 (number) - 左边
+ right: 500 (number) - 右边
        
## Coordinate (Sheet Identify) - 操作区域坐标对象
+ coordinate (Coordinate properties) - 选中区域坐标

## Coordinate properties (object) - 操作区域坐标属性列表
+ startCol: 1(number) - 选中区域开始列号
+ startRow: 1(number) - 选中区域开始行号
+ endCol: 1(number) - 选中区域结束列号
+ endRow: 1(number) - 选中区域结束行号
    
## Operation Coordinate (object) - 不管是原始操作位还是选择区域，传递时只需要给出具体以哪个点为操作点
    
+ oprCol: 4 (number) - 列坐标点
+ oprRow: 6 (number) - 行坐标点

## Paste Object(Col Number) - 粘贴进来的格式化对象
+ content: `example: paste content, testing, 123, <script>alert('sql insert')</script> and 中文` - 粘贴的内容
+ row: 1 (number) - 相对于初始位置的距离
+ col: 3 (number) - 相对于初始位置的距离

## Vaildate Object (object) - 数据验证对象，选择区域表示：${列名}${行名称}（左上）:${列名称}${行名称}（右下）当整行、列选择时，省略统一位置：${位置}:${位置}

+ formula1: `min` (string) - 可能不存在
+ formula2: `max` (string) - 可能不存在
+ type: 4 (number) - 数据类型