FORMAT: 1A
HOST: http://www.fn.com

# Interaction API of FN

> 为保证我们的设计思想和开发成果保持一致，采用互动性文档进行的结果验证，其功能包含几个方面
> - 文档的生成
> - 数据请求结果记录
> - 在线编辑文档内容
> - 模拟数据，正式环境数据
> - 文档和开发结果匹配测试


## 阅读&使用须知

### 全局变量

> - `SPREADSHEET_AUTHENTIC_KEY`: 当前页面的唯一`FNID`, 不管是新建或更新表
> - `SPREADSHEET_BUILD_STATE`: 当前表的状态，新建或者更新，如果是更新表需要发起请求数据内容的操作

### REST命名规则

> `url`的组成结构： `{根目录}/{模块}/{操作- ?子操作}` 
> 模块有4中类型，`Table`,`Sheet`,`Row|Col`,`Cell`
> 操作根据具体层级关系递进，中间用 `-` 间隔
>> 如 设置字体颜色，`http://www.fn.com/cell/font-color`

### 文档缺陷

> 由于文档没有实现`Headers`的重用
> 所有我们在Mock时，自定在`Headers`里面指定`FN-Step`、`FN-ID`信息

### 传递参数的意义解释

> 交互阶段传入的坐标信息都是`sort`值，即：后台数据存储的行列索引值
> 整行、列操作时，最大值用-1表示
>> 如：第五列
>>```
>> {
>>      startRow: 0,
>>      startCol: 4,
>>      endRow：-1,
>>      endCol: 5
>>}
>>```

### 留存的疑问

> - position的参数都是什么意思？
> - 冻结操作，在还原时有bug
> - 没有传递变量的功能，如何解决？

### 困难解决记录

> - optional 和 required的区别，和作用
>> optional后面必须跟Member成员
>> required是必须参数，不能选择
>
> - 怎么进行值传递，参数变量
>>API的point功能可以实现

# Group Opration Row or Col

## Rows Opration [/row/{actionType}]

    行操作，插入，删除，隐藏，显示，行高调整
    
+ Parameters
    + actionType: `plus` (enum[string]) - 动作类型
        + Members
            + `plus`
            + `reduce`
            + `hide`
            + `show`

### Single Insert or Delete Row [POST]

+ Request (application/json)
    + Attributes (Row Number)
    
+ Response 200

## Adjust Single Row Height [POST /row/adjust]
    行高调整
+ Request (application/json)
    + Attributes (Row Number)
        + offset: `87`(number) - 调整后的值,最小值为5px
    
+ Response 200

## Batch Add Rows [POST /row/plus-batch]
    
    批量增加列
    
+ Request (application/json)
    + Attributes
        + num: 30(number) - 增加的数量

+ Response 200

## Cols Opration [/col/{actionType}]

    列操作，插入，删除，隐藏，显示，调整
    
+ Parameters
    + actionType: `plus` (enum[string]) - 动作类型
        + Members
            + `plus`
            + `reduce`
            + `hide`
            + `show`

### Single Insert or Delete Col [POST]
    
+ Request (application/json)
    + Attributes (Col Number)
    
+ Response 200

## Adjust Single Col Width [POST /col/adjust]

    列宽调整
    
+ Request (application/json)
    + Attributes (Col Number)
        + offset: `87`(number) - 调整后的值,最小值为5px
    
+ Response 200

## Batch Add Cols [POST /col/plus-batch]
    
    批量增加列
    
+ Request (application/json)
    + Attributes
        + num: 30(number) - 增加的数量

+ Response 200
    

# Group Opration Cells

    针对单元格的处理，即使没有内容也有效果
    
## Merge or Split [/cell/{actionType}]

+ Parameters
    + actionType: `merge`(string) - 动作类型
        + Members
            + `merge`
            + `split`

### Merge or Split Cells [POST]

+ Request (application/json)
    
    + Attributes (Coordinate)

+ Response 200

## Borders [/cell/border]

### Set Borders Style [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + direction: `top` (enum[string])
            + Members
                + `top`
                + `right`
                + `bottom`
                + `left`
                + `all`
                + `outer`
                + `none`

+ Response 200

## Set Background [/cell/bg]

### Setting Background Color [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + color: `#000` (string) - 编码遵循RGB的规则编码，以后还需要加入透明
    
+ Response 200

# Group Cell Data Opration

    针对单元格的内容处理的操作，有内容时才有效果

## Align transverse [/cell/align-landscape]

### Set transverse Style [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + align: `left` (enum[string])
            + Members
                + `left`
                + `center`
                + `right`
+ Response 200

## Align vertically [/cell/align-portrait]

### Set vertically Style [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + align: `top` (enum[string])
            + Members
                + `top`
                + `middle`
                + `bottom`
+ Response 200

## Format Cells Type [/cell/format]

    单元格的类型设置

### Setting Cells Type [POST]
    
+ Request (application/json)
    + Attributes (Coordinate)
        + format:`routine`(enum[string]) - 常规类型
            + Members
                + `routine` - 常规类型
                + `text`
                + `number`
                + `date`
                + `currency`
                + `percent`
        + express: `###.##`(string) - 格式表达式，限制性的解释POI中的规则，如果超出解释范围就为默认类型

+ Response 200

## Set Content [/cell/content]

### Setting Data Content [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + content: `<script>console.log("1")</script>`(string) - 输入的内容，内容需要经过转码的，防止代码攻击

+ Response 200

## Clear Content [/cell/clean]

    用户可以通过操作，直接删除单元格的所有内容

### Delete Cells All Info [POST]

+ Request (application/json)
    + Attributes (Coordinate)

+ Response 200

## Add or Update Comments [/cell/comment-plus]

### Setting Data Comments for explain [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + comment: `<script>console.log("1")</script>`(string, required) - 输入的内容，内容需要经过转码的，防止代码攻击

+ Response 200

## Delete Comments [/cell/comment-reduce]

### Delete Data Comments [POST]

+ Request (application/json)
    + Attributes (Coordinate)

+ Response 200

# Group Cells Font Style Opration

    针对单元格内的字体的接口

## Font Size [/cell/font-size]

### Update Font Size [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + size: `12`(number) - 字体默认是12pt，最大值48，都是以pt为单位
        
+ Response 200

## Font Family [/cell/font-family]

### Update Font Family [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + family: `宋体`(enum[string]) - 字体默认是宋体，其余字体风格是枚举类型
            + Members
                + `宋体`
                + `微软雅黑`
                + `黑体`
                + `Tahoma`
                + `Arial`
                + `楷体`
        
+ Response 200

## Font Weight [/cell/font-weight]

### Update Font Weight [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + weight: 700 (number) - 字体默认是700，其余选项是枚举类型从100-900
        
+ Response 200

## Font Italic [/cell/font-italic]

### Update Font Italic [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + italic: false (boolean) - 默认为非斜体
        
+ Response 200

## Font Color [/cell/font-color]

### Update Font Color [POST]

+ Request (application/json)
    + Attributes (Coordinate)
        + color: `#000` (string) - 编码遵循RGB的规则编码
    
+ Response 200

# Group Table Opration

## Table Reload [/reload]

### Reload All Info [POST]

+ Request (application/json)
    + Attributes (Area px Info)

+ Response 200 (application/json)
    
        {
            "info":"这部分model结构有很多参数还不清楚，而且json结构层次太多，暂时不显示"
        }

# Group Sheet Opration

## Table Paste [/sheet/paste]

+ Attributes (object)
    + col: 4 (number) - 粘贴时列坐标点
    + row: 6 (number) - 粘贴时行坐标点
    + content:`this is paste content`(string) - 粘进来的内容

### Paste All Info to Any Where [POST]

+ Request (application/json)
    + Attributes (array[Table Paste])
        
+ Response 200
    + Attributes (object)
        + isLegal: true(boolean) - 是否合法

## Table Cut & Copy [/sheet/{actionType}]

+ Parameters
    + actionType: `cut`(string)
        这个动作是剪切或者复制，这个动作的触发只能在excel出现，跟外部交互的操作都是粘贴操作，
        由于浏览器的保护，数据不能获取被剪切到外部的事件
        + Members
            + `cut`
            + `copy`

### Cut or Copy Info to Any Where [POST]

+ Request (application/json)
    + Attributes (object)
        + orignal (Coordinate properties) - 数据原来的位置
        + target (Orignal Coordinate)
        
+ Response 200

## Frozen View [/sheet/frozen]

+ Attributes (Orignal Coordinate)
    + viewRow: 45(number) - 冻结时，用户可以看到范围，行编号
    + viewCol: 0 (number) - 冻结时，用户看见的范围，列编号

### Frozen Position [POST]

    不管冻结怎么冻结，只需要把坐标传给后台就行了
    
+ Request (application/json)
    + Attributes (Frozen View)
        
+ Response 200

### UnFrozen Position [GET]

    解除冻结视图

+ Response 200

## Undo [/sheet/undo]

    后退操作
    
### Undo Oprtaion [GET]
    

+ Response 200

## Redo [/sheet/redo]

    前进操作
    
### Redo Opration [GET]

+ Response 200

## Batch Load Area Information [/sheet/area]

### Load Area

+ Request (application/json)
    + Attributes (Area px Info)
        
+ Response 200 (application/json)

        {
            "info":"这部分model结构有很多参数还不清楚，而且json结构层次太多，暂时不显示"
        }

# Data Structures

## Sheet Identify (object) - 单个sheet的ID标识
+ sheetId: `1` (string) - 字符串类型的sheetId，自增的整数

## Routine (object) - 正常的返回值
+ returncode: 200 (number) - http的编码
+ returndata: true (boolean) - 返回数据的情况

## Col Number (Sheet Identify)
+ col: 1(number) - 列号

## Row Number (Sheet Identify)
+ row: 1(number) - 行号

## Area px Info (object)
+ top: 1117 (number) - 请求区域的顶部像素
+ bottom: 1537 (number) - 低部
+ left: 0 - 左边
+ right: 500 - 右边
        
## Coordinate (Sheet Identify) - 操作区域坐标对象
+ coordinate (Coordinate properties) - 选中区域坐标

## Coordinate properties (object) - 操作区域坐标属性列表
+ startCol:1(number) - 选中区域开始列号
+ startRow:1(number) - 选中区域开始行号
+ endCol:1(number) - 选中区域结束列号
+ endRow:1(number) - 选中区域结束行号
    
## Orignal Coordinate (object) - 不管最终选择区域落在什么位置, 这个信息都是 鼠标第一次指定的坐标值
+ orignalCol: 4 (number) - 列坐标点
+ orignalRow: 6 (number) - 行坐标点